// <auto-generated />
namespace TravelTripProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_addadmin_column_email : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_addadmin_column_email));
        
        string IMigrationMetadata.Id
        {
            get { return "202208141125009_mig_addadmin_column_email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
